#!/bin/bash

UB_PID_FILE="/tmp/.$(uuidgen)"
ueberzugpp layer --output=$IMG --no-stdin --silent --use-escape-codes --pid-file $UB_PID_FILE
UB_PID=$(cat $UB_PID_FILE)

export SOCKET=/tmp/ueberzugpp-$UB_PID.socket
export X=$(($(tput cols) / 2 + 1))

function previewer {
  case "$1" in
    *.jpg|*.png) ueberzugpp cmd -s $SOCKET -i fzfpreview -a add -x $X -y 1 --max-width $FZF_PREVIEW_COLUMNS --max-height $FZF_PREVIEW_LINES -f "$1" || echo "no ueberzugpp :(" ;;
    *) ueberzugpp cmd -s $SOCKET -a exit && bat --style plain --color=always "$1" || echo "no bat :(" ;;
  esac
}

export -f previewer
SHELL="$(which bash)" fzf --preview "previewer {}" \
                          --bind='alt-j:clear-screen+refresh-preview+down' \
                          --bind='alt-k:clear-screen+refresh-preview+up' \
                          "${@}"

ueberzugpp cmd -s $SOCKET -a exit
