#!/bin/bash

# https://www.reddit.com/r/hyprland/comments/17cx5uj/battery_notification_when_less_than_20
while true; do
  bat_lvl=$(cat /sys/class/power_supply/BAT0/capacity)
  if [ "$bat_lvl" -le 20 ]; then
    notify-send --urgency=CRITICAL "Battery Low" "Level: ${bat_lvl}%"
    sleep 1200
  else
    sleep 60
  fi
done

# ╭─────╮
# │ TTS │
# ╰─────╯
# nix-env -iA nixpkgs.mimic
# cat /sys/class/power_supply/BAT0/status   | awk '$1 == "Discharging" {exit 1}' &&
# cat /sys/class/power_supply/BAT0/capacity | awk '$1 >= 95 {system("mimic -voice slt_hts -t complete-charge") }'
# cat /sys/class/power_supply/BAT0/status   | awk '$1 == "Charging" {exit 1}' &&
# cat /sys/class/power_supply/BAT0/capacity | awk '$1 <= 15 {system("mimic -voice slt_hts -t "$1"-percent") } ; $1 <= 5 {system("notify-send -u critical " $1 "% discharging\n") }'
