#!/bin/sh

read -p "reset to essential packages? [y/N]" ans
[ "$ans" != "y" ] && exit

# https://wiki.archlinux.org/title/Pacman/Tips_and_tricks#List_of_installed_packages
# pacman -Qqe

# https://wiki.archlinux.org/title/Pacman/Tips_and_tricks#Removing_everything_but_essential_packages
sudo pacman -D --asdeps $(pacman -Qqe)
sudo pacman -D --asexplicit \
base \
base-devel \
brightnessctl \
broadcom-wl \
dosfstools \
dunst \
exfat-utils \
gammastep \
git \
gnome-keyring \
google-chrome \
grim \
grub \
hyprland \
intel-ucode \
libnotify \
linux \
linux-firmware \
network-manager-applet \
noto-fonts \
noto-fonts-emoji \
ntfs-3g \
pipewire-pulse \
playerctl \
slurp \
swaybg \
visual-studio-code-bin \
vlc \
vlc-plugin-ffmpeg \
vlc-plugin-freetype \
waybar \
wezterm-nightly-bin \
wl-clipboard \
wmenu \
xdg-desktop-portal-hyprland \
yay-bin \
zathura-pdf-poppler \
zram-generator \
zsh
# playerctl \             # for chrome player
# vulkan-intel \          # for zed
# vulkan-radeon \         # DRI_PRIME=1 windsurf
# zed \
# radeontop \

# https://wiki.archlinux.org/title/Pacman/Tips_and_tricks#Removing_unused_packages_(orphans)
sudo pacman -Rscn $(pacman -Qtdq)
sudo pacman -Fy
yes | sudo pacman -Scc

## keyring required if long time not updating archlinux
# sudo pacman -Sy archlinux-keyring
# sudo pacman -Syu

# install dotfiles
(
  ln -sf $(git rev-parse --show-toplevel)/.config/shell/.zprofile  ~/.zprofile

  sudo systemctl     enable NetworkManager       # wifi
  systemctl   --user enable pipewire-pulse       # audio
  # systemctl --user enable xdg-desktop-portal   # to share screen on meet.google.com (not required anymore)

  echo '%sudo ALL=(ALL:ALL)  NOPASSWD: ALL'                             | sudo tee /etc/sudoers.d/sudo
  echo '%wheel ALL=(ALL:ALL) NOPASSWD: ALL'                             | sudo tee /etc/sudoers.d/wheel
  echo 'Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch' | sudo tee /etc/pacman.d/mirrorlist

  sudo chsh --shell /bin/zsh $USER
)

# AUR
[ ! -e /bin/yay ] &&
(
  git clone https://aur.archlinux.org/yay-bin.git /tmp/yay
  cd /tmp/yay
  yes | makepkg -si
  yay -S --noconfirm visual-studio-code-bin google-chrome wezterm-nightly-bin
  yay -Ps
  code --install-extension yeferyv.retronvim
)
