#!/bin/sh

read -p "reset to essential packages? [y/N]" ans
[ "$ans" != "y" ] && exit

# https://wiki.archlinux.org/title/Pacman/Tips_and_tricks#List_of_installed_packages
# pacman -Qqe

# https://wiki.archlinux.org/title/Pacman/Tips_and_tricks#Removing_everything_but_essential_packages
sudo pacman -D --asdeps $(pacman -Qqe)
sudo pacman -D --asexplicit \
base \
base-devel \
brightnessctl \
broadcom-wl \
dosfstools \
dunst \
exfat-utils \
gammastep \
git \
gnome-keyring \
grim \
grub \
hyprland \
intel-ucode \
libnotify \
linux \
linux-firmware \
mpd \
mpv-mpris \
rmpc \
network-manager-applet \
noto-fonts \
noto-fonts-emoji \
ntfs-3g \
pipewire-pulse \
playerctl \
slurp \
swaybg \
ttf-firacode-nerd \
waybar \
wezterm \
wl-clipboard \
wmenu \
zathura-pdf-poppler \
zram-generator \
zsh
# playerctl \             # for chrome player
# xdg-desktop-portal-wlr\ # for meet.google.com
# vulkan-intel \          # for zed
# vulkan-radeon \         # DRI_PRIME=1 windsurf
# zed \
# radeontop \

# https://wiki.archlinux.org/title/Pacman/Tips_and_tricks#Removing_unused_packages_(orphans)
sudo pacman -Rscn $(pacman -Qtdq)
sudo pacman -Fy
yes | pacman -Scc

# install dotfiles
(
  ln -sf $(git rev-parse --show-toplevel)/.config/shell/.zprofile  ~/.zprofile
  mkdir -p ~/.local/share/mpd

  systemctl --user enable pipewire-pulse
  systemctl --user enable mpd
  sudo systemctl   enable NetworkManager
  # sudo systemctl   enable xdg-desktop-portal-wlr # to share screen on meet.google.com

  echo '%sudo ALL=(ALL:ALL)  NOPASSWD: ALL'                             | sudo tee /etc/sudoers.d/sudo
  echo '%wheel ALL=(ALL:ALL) NOPASSWD: ALL'                             | sudo tee /etc/sudoers.d/wheel
  echo 'Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch' | sudo tee /etc/pacman.d/mirrorlist

  sudo chsh --shell /bin/zsh $USER
)

# AUR
(
  git clone https://aur.archlinux.org/yay-bin.git
  cd yay-bin
  yes | makepkg -si
  yay -S visual-studio-code-bin google-chrome
  yay -Ps
  code --install-extension yeferyv.retronvim
)
