#!/bin/bash
#https://github.com/gokcehan/lf/issues/626

# To skip cleanup
# if [ "$1" != "$f" ]; then
#   case "$(file -Lb --mime-type -- "$f")" in
#     image/*) exit;;
#   esac
# fi

[[ -e "$UB_SOCKET" ]] && ueberzugpp cmd -s $UB_SOCKET -a remove -i PREVIEW && exit 0
[[ -z $TMUX ]] && [[ -z $NVIM ]] &&
  kitty +icat --clear --silent --transfer-mode memory < /dev/null > /dev/tty ||
  killall -s SIGWINCH lf nvim
