#!/bin/bash
#https://github.com/gokcehan/lf/wiki/Previews

set -e

if [ -n "$DISPLAY" ]; then
  export FIFO_UEBERZUG="${TMPDIR:-/tmp}/lf-ueberzug-$$"

  cleanup() {
    exec 3>&-
    rm "$FIFO_UEBERZUG"
  }

  mkfifo "$FIFO_UEBERZUG"

  # cat <$FIFO_UEBERZUG | while read msg ; do
  # # >/dev/tty cat <$msg; #sixel_format
  # # >/dev/tty img2sixel -w 400 $msg;
  # # >/dev/tty img2sixel -w 400 $(echo $msg | jq .path | tr '"' ' ');
  # >/dev/tty img2sixel -w 400 $(echo $msg | awk -F':' '{print $9}'| awk -F'"' '{print $2}' );
  # done &

  ueberzug layer -s <"$FIFO_UEBERZUG" &

  #cat <"$FIFO_UEBERZUG" &
  exec 3>"$FIFO_UEBERZUG"
  trap cleanup EXIT

  if ! [ -d "$HOME/.cache/lf" ]; then
    mkdir -p "$HOME/.cache/lf"
  fi

  lf "$@" 3>&-
else
  exec lf "$@"
fi
