customCommands:
  - key: 'g'
    context: files

  - key: 'g'
    context: commits

  - key: 'g'
    context: localBranches

gui:
  showIcons: true
  theme:
    activeBorderColor:
      - "#4c4c4c"
      - bold
    inactiveBorderColor:
      - "#2c2c2c"
    selectedLineBgColor:
      - "#0c0c0c"
    selectedRangeBgColor:
      - "#0c0c0c"
    defaultFgColor:
      - "#6c6c6c"

git:
  parseEmoji: true
  log:
    showGraph: 'always'
    showWholeGraph: true
