#!/bin/sh

## Use neovim for vim if present.
# [ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# _sudo_not_required_for_some_system_commands_
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# _verbosity_and_settings_that_you_pretty_much_just_always_are_going_to_want_
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkdir="mkdir -pv" \
	# youtubeaudiowebm="youtube-dl --add-metadata --ignore-errors --write-thumbnail --format bestaudio " \
	# youtubeaudioopus="youtube-dl --add-metadata --ignore-errors --write-thumbnail --extract-audio --format bestaudio/best " \
	# youtubevidaudiosub="youtube-dl --add-metadata --ignore-errors --write-auto-sub --write-sub --format 'bestvideo+bestaudio' " \
	# youtubevidsub720="youtube-dl --add-metadata --ignore-errors --write-auto-sub --write-sub --format 'bestvideo[height<=720]+bestaudio' " \
	# youtubevidsub480="youtube-dl --add-metadata --ignore-errors --write-auto-sub --write-sub --format 'bestvideo[height<=480]+bestaudio' " \
	# youtubevidsub360="youtube-dl --add-metadata --ignore-errors --write-auto-sub --write-sub --format 'bestvideo[height<=360]+bestaudio' " \
	# youtubevid720="yt-dlp --add-metadata --format 'bestvideo[height<=720]+bestaudio' " \
	# youtubearia2c="yt-dlp --add-metadata --external-downloader aria2c --external-downloader-args '-c -j 5 -x 5 -s 5 -k 1M'" \
  # ffmpeg360="	ffmpeg=' for File in *; { [ -f '$File' ] || continue; ffmpeg -i '$File' -s 640x360 -c:a copy '../path/to/folder/${File}' ; }'"\
	# pythondocs="python -m pydoc -p 8989" \
	# stowdotfiles="cd /home/dtfls/Dotfiles && stow --restow --verbose --simulate --target=$HOME/.config .config" \
	# gitshow="git show --all" \
	# gitlodag="git log --oneline --decorate --all --graph" \
	# gitloghelp="git log --help" \
	# gitlog="git log --oneline --graph" \
	# gitlogcompletion="git log --<TAB>" \
	# gitrestorepatch="git restore --staged --patch" \
  # vncstart="vncpasswd && vncserver :1 #to connect use vncviewer (view vncserver log for 'server:port')" \
	# gnome-keyring-vscodium="gnome-keyring-daemon --start --foreground --components=secrets" \


# _colorize_commands_when_possible_
alias \
	ll="ls -lha --hyperlink=auto --color=auto --group-directories-first" \
	ls="ls      --hyperlink=auto --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	pacman="sudo pacman --noconfirm" \
	cht="cht.sh" \
	# cht="cheat-sh" \

# _vim_tmux_status_aliases_
alias \
  lvim="NVIM_APPNAME=lunarvim nvim" \
  vi="NVIM_APPNAME=nvchad nvim" \
  vim="NVIM_APPNAME=astronvim nvim" \
  vscodevim="NVIM_APPNAME=vscode-neovim nvim" \
	nvimdiff="nvim -d" \
	nvimterminal="nvim -c 'set nonumber | terminal zsh'" \
	tmuxconf="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf" \
	tmuxattach="tmux attach" \
	tmuxssh="ssh -t <user@host> tmux" \
	tmuxlist="tmux ls" \
	tmuxkillall="tmux kill-session -a" \
	tmuxmpvdmenu="tmux new -d mpv --loop-playlist --no-video $1" \
	# ref="~/.local/bin/i3cmds/shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	# volumebar="echo '♪: $(pamixer --get-volume-human)'" \
	# batterybar="acpi | sed 's/Battery [0-9]: //;s/[Dd]ischarging, /🔋/;s/[Nn]ot charging, /🛑/;s/[Cc]harging, /🔌/;s/[Uu]nknown, /♻️/;s/[Ff]ull, /⚡/;s/,.*//'" \
	# freebar="free -h | awk '/^Mem:/ {printf "%s/%s",$3,$7}'" \
	# datebar="date +'%F %T'" \
	# refbar="kill '$(pstree -lp | grep -- -dwmbar\([0-9] | sed "s/.*sleep(\([0-9]\+\)).*/\1/")'" \
