gui:
  showIcons: true
  theme:
    activeBorderColor:
      - "#2c2c2c"
      - bold
    inactiveBorderColor:
      - "#2c2c2c"
    selectedLineBgColor:
      - "#0c0c0c"
    selectedRangeBgColor:
      - "#0c0c0c"
    defaultFgColor:
      - "#2c2c2c"

git:
  parseEmoji: true
  log:
    showGraph: 'always'
    showWholeGraph: true
