format = """
$battery\
$sudo\
$username\
$custom\
$git_branch\
$git_status\
$cmd_duration\
$status\
$package\
$character\
"""

# Timeout 1 min
command_timeout = 60000
add_newline = false

[cmd_duration]
min_time = 60000

[directory]
disabled = false
style = "bold fg:#555555"
format = "[$path ]($style)"
truncation_length = 9
# truncation_symbol = "…/"

[character] # The name of the module we are configuring is "character"
success_symbol = "[󰞷 ](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[󰞷 ](bold red)"
vimcmd_symbol =	"[󰞷 ](bold green)"
vimcmd_replace_one_symbol =	"[󰞷 ](bold purple)"
vimcmd_replace_symbol =	"[󰞷 ](bold purple)"
vimcmd_visual_symbol =	"[󰞷 ](bold yellow)"
format = "$symbol"

[custom.home]
when = """ test "$HOME" = "$PWD" """
format = ""
# format = """[󰞷 ](fg:#0000ff)"""

[custom.gitroot]
command = """
[ "${PWD:A}" = "$PWD" ] && {
    GIT_ROOT=$(git rev-parse --show-toplevel)
    DIR="$GIT_ROOT:t${${PWD}#$~~GIT_ROOT}"
  }||{
    DIR=$PWD
  }
  echo ${DIR/$HOME/\\~}
"""
when = """ test "$HOME" != "$PWD" """
format = """[$output](bold fg:#555555) """
