-- colorschemes
-- vim.cmd [[ colorscheme lunar2-generated ]]
-- vim.cmd [[ colorscheme lunar2 ]]
-- vim.cmd [[ colorscheme leet]]

require "user.autocommands"
require "user.options"
require "user.lazy"
-- require "user.aerial"
require "user.alpha"
-- require "user.bufferline"
-- require "user.colorizer"
require "user.colorscheme"
-- require "user.cmp"
-- require "user.cmp-tabnine"
require "user.dap"
require "user.keymaps"
require "user.illuminate"
require "user.indentline"
require "user.lsp"
-- require "user.lspsaga"
require "user.lualine"
require "user.mini"
-- require "user.neo-tree"
-- require "user.neoclip"
require "user.project"
-- require "user.telescope"
require "user.toggleterm"
require "user.treesitter"
require "user.whichkey"
